service:
  blacklist:
    chargen_dgram:
      name:
        CentOS Linux-6: chargen-dgram
        CentOS Linux-7: chargen-dgram
      description:
      tags:
        CentOS Linux-6: CIS-2.1.12
        CentOS Linux-7: CIS-2.1.12

    chargen_stream:
      name:
        CentOS Linux-6: chargen-stream
        CentOS Linux-7: chargen-stream
      description:
      tags:
        CentOS Linux-6: CIS-2.1.13
        CentOS Linux-7: CIS-2.1.13

    daytime_dgram:
      name:
        CentOS Linux-6: daytime_dgram
        CentOS Linux-7: daytime_dgram
      description:
      tags:
        CentOS Linux-6: CIS-2.1.14
        CentOS Linux-7: CIS-2.1.14

    daytime_stream:
      name:
        CentOS Linux-6: daytime-stream
        CentOS Linux-7: daytime-stream
      description:
      tags:
        CentOS Linux-6: CIS-2.1.15
        CentOS Linux-7: CIS-2.1.15

    echo_dgram:
      name:
        CentOS Linux-6: echo-dgram
        CentOS Linux-7: echo-dgram
      description:
      tags:
        CentOS Linux-6: CIS-2.1.16
        CentOS Linux-7: CIS-2.1.16

    echo_stream:
      name:
        CentOS Linux-6: echo-stream
        CentOS Linux-7: echo-stream
      description:
      tags:
        CentOS Linux-6: CIS-2.1.17
        CentOS Linux-7: CIS-2.1.17

    tcpmux_server:
      name:
        CentOS Linux-6: tcpmux-server
        CentOS Linux-7: tcpmux-server
      description:
      tags:
        CentOS Linux-6: CIS-2.1.18
        CentOS Linux-7: CIS-2.1.18

    avahi:
      name:
        CentOS Linux-6: avahi-daemon
        CentOS Linux-7: avahi-daemon
      description:
      tags:
        CentOS Linux-6: CIS-3.3
        CentOS Linux-7: CIS-3.3

    dhcp_server:
      name:
        CentOS Linux-6: dhcpd
        CentOS Linux-7: dhcpd
      description:
      tags:
        CentOS Linux-6: CIS-3.5
        CentOS Linux-7: CIS-3.5

