service:
  blacklist:

    chargen:
      name:
        Debian-8: chargen
        CentOS Linux-6: ['chargen-dgram', 'chargen-stream']
        CentOS Linux-7: ['chargen-dgram', 'chargen-stream']
      description:
      tags:
        Debian-8: CIS-5.2
        CentOS Linux-6: ['CIS-2.1.12', 'CIS-2.1.13']
        CentOS Linux-7: ['CIS-2.1.12', 'CIS-2.1.13']

    daytime:
      name:
        Debian-8: daytime
        CentOS Linux-6: ['daytime-dgram', 'daytime-stream']
        CentOS Linux-7: ['daytime-dgram', 'daytime-stream']
      description:
      tags:
        Debian-8: CIS-5.3
        CentOS Linux-6: ['CIS-2.1.14', 'CIS-2.1.15']
        CentOS Linux-7: ['CIS-2.1.14', 'CIS-2.1.15']

    echo:
      name:
        Debian-8: echo
        CentOS Linux-6: ['echo-dgram', 'echo-stream']
        CentOS Linux-7: ['echo-dgram', 'echo-stream']
      description:
      tags:
        Debian-8: CIS-5.4
        CentOS Linux-6: ['CIS-2.1.16', 'CIS-2.1.17']
        CentOS Linux-7: ['CIS-2.1.16', 'CIS-2.1.17']

    tcpmux_server:
      name:
        CentOS Linux-6: tcpmux-server
        CentOS Linux-7: tcpmux-server
      description:
      tags:
        CentOS Linux-6: CIS-2.1.18
        CentOS Linux-7: CIS-2.1.18

    avahi:
      name:
        Debian-8: avahi-daemon
        CentOS Linux-6: avahi-daemon
        CentOS Linux-7: avahi-daemon
      description:
      tags:
        Debian-8: CIS-6.2
        CentOS Linux-6: CIS-3.3
        CentOS Linux-7: CIS-3.3

    dhcp_server:
      name:
        Debian-8: isc-dhcp-server
        CentOS Linux-6: dhcp
        CentOS Linux-7: dhcp
      description:
      tags:
        Debian-8: CIS-6.4
        CentOS Linux-6: CIS-3.5
        CentOS Linux-7: CIS-3.5

    discard:
      name:
        Debian-8: discard
      description:
      tags:
        Debian-8: CIS-5.5

    time:
      name:
        Debian-8: time
      description:
      tags:
        Debian-8: CIS-5.6

